const Productos = [
    { id: 1,
      nombre: "Creatina 150g",  
      precio: 3500,
      stock:5,
      imagen: "images/creatina150g.png",
    },
    { id: 2,
        nombre: "Whey protein NITRO",  
        precio: 5500,
        stock:5,
        imagen: "images/wheynitrov.png",
      },
      { id: 3,
        nombre: "Whey protein",  
        precio: 4500,
        stock:5,
        imagen: "images/whey2lbv.png",
      },
      { id: 4,
        nombre: "Multivitaminico",  
        precio: 2500,
        stock:5,
        imagen: "images/vitaminas.png",
      },
      { id: 5,
        nombre: "Whey protein Avena",  
        precio: 4500,
        stock:5,
        imagen: "images/wheyavena.png",
      },
      { id: 6,
        nombre: "Whey protein WOMAN",  
        precio: 4500,
        stock:5,
        imagen: "images/wheywoman.png",
      },

];